name: GitLeaks Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run GitLeaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ github.actor }}

      - name: Send GitHub Actions Report to Slack
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "text": "GitLeaks scan detected leaks in repository `${{ github.repository }}` triggered by `${{ github.actor }}`.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitLeaks Alert:*\nLeaks were detected in repository `${{ github.repository }}`\nTriggered by: `${{ github.actor }}`"
                  }
                }
              ]
            }
          webhook: "https://hooks.slack.com/services/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"
          webhook-type: incoming-webhook
