name: GitLeaks Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install GitLeaks
        run: |
          uname -m
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.2/gitleaks_8.24.2_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz

      - name: Run GitLeaks
        id: gitleaks
        run: |
          # Running GitLeaks; the command exits non-zero if leaks are detected.
          ./gitleaks detect --source .


