name: GitLeaks Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.2.10/gitleaks_8.2.10_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks
        id: gitleaks
        run: |
          # Running GitLeaks; exit code will be non-zero if leaks are detected.
          gitleaks detect --source . --report-format json --report-path gitleaks-report.json || true

      - name: Check for Leaks
        id: check_leaks
        run: |
          if grep -q "Description" gitleaks-report.json; then
            echo "::set-output name=leaks_found::true"
          else
            echo "::set-output name=leaks_found::false"
          fi

      - name: Send Slack Notification
        if: steps.check_leaks.outputs.leaks_found == 'true'
        run: |
          message="*GitLeaks Alert in ${{ github.repository }}*%0APotential secrets were detected during the scan.%0A<https://github.com/${{ github.repository }}/actions|View Workflow Details>"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$message\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
